app/admin/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user
from sqlalchemy import func

from app.forms import MusicProductForm, ProductForm, SongForm, UserEditForm
from app.models import AlbumGenre, Albums, Artists, Genres, OrderItems, Orders, Products, Songs, Users
from app.extensions import db
from app.decorators import role_required

# Initialisation of admin blueprint
admin_bp = Blueprint('admin', __name__, template_folder='templates')


# Route for admin home page

@admin_bp.route('/')
@role_required('Admin')
def admin_home():
    return render_template('admin.html')


# Route for admin product management page

@admin_bp.route('/products', methods=['GET', 'POST'])
@role_required('Admin')
def admin_products():
    """Function for admin product page which displays all products and also allows for editing and deleting products"""

    # Queries database for all products
    products = db.session.query(Products).all()
    # Initialise ProductForm class
    product_form = ProductForm()
    # If request is PUT to update a product
    if product_form.validate():
        # Checks if product already exists
        if product_form.product_id.data:
            # Edit (PUT) request for updating existing product
            product = Products.query.get(product_form.product_id.data)
            product_form.populate_obj(product)
            db.session.commit()

            flash('Product Edited Successfully', 'success')
            return redirect(url_for('admin.admin_products'))
        else:
            # Add (POST) request for new product
            product = Products(name=request.form['name'],
                               image=request.form['image'],
                               price=request.form['price'],
                               type=request.form['type'],
                               stock=request.form['stock'])
            db.session.add(product)
            db.session.commit()

            flash('Product Added Successfully', 'success')
            return redirect(url_for('admin.admin_products'))

    return render_template('adminProducts.html', products=products, product_form=product_form)


# Route for deleting products based on id

@admin_bp.route('products/delete/<int:id>', methods=['GET', 'POST'])
@role_required('Admin')
def delete_product(id):
    """Function for deleting products based on id"""

    # Queries datababase for product deletion
    product = db.session.query(Products).get(id)
    db.session.delete(product)
    db.session.commit()
    flash('Product Deleted Successfully', 'success')

    return redirect(url_for('admin.admin_products'))


# Route for viewing product details and CRUD functionality for songs associated with an album

@admin_bp.route('/products/details/<int:id>', methods=['GET', 'POST'])
@role_required('Admin')
def admin_product_details(id):
    """Function for displaying album data for music products and CRUD functionality for songs"""

    # Queries database for product based on id
    product = Products.query.get(id)
    # Queries database to retrieve genres related to the album
    genres = Genres.query.join(AlbumGenre).filter_by(
        fk_album_id=product.music_info.album_id)
    product = db.session.query(Products).filter_by(product_id=id).first()

    # Initialises SongForm form class
    song_form = SongForm()
    if song_form.validate_on_submit():
        # Checks if song already exists
        if song_form.song_id.data:
            song = db.session.query(Songs).get(song_form.song_id.data)
            song_form.populate_obj(song)

            db.session.commit()

            flash('Song Edited Successfully', 'success')
            return redirect(url_for('admin.admin_product_details', id=id))
        else:
            song = Songs(name=song_form.name.data,
                         length=song_form.length.data,
                         fk_album_id=product.music_info.album_id)

            db.session.add(song)
            db.session.commit()

            flash('Song Added Successfully', 'success')
            return redirect(url_for('admin.admin_product_details', id=id))

    return render_template('adminProductDetails.html', product_id=id, product=product, genres=genres, song_form=song_form)


# Route for setting the product details

@admin_bp.route('/products/details/<int:id>/set', methods=['GET', 'POST'])
@role_required('Admin')
def set_product_details(id):
    # Initialise MusicProductForm class for music data
    details_form = MusicProductForm()
    # Extracts all the genres from the database for input
    details_form.genres.choices = [
        (genre.genre_id, genre.name) for genre in Genres.query.all()]

    if details_form.validate_on_submit():
        album_name = details_form.album_name.data
        year = details_form.year.data
        artist_name = details_form.artist_name.data
        bio = details_form.artist_bio.data

        artist = Artists.query.filter_by(name=artist_name).first()
        # Checks if the artist already exists in the database
        if artist == None:
            artist = Artists(name=artist_name, bio=bio)

            db.session.add(artist)
            db.session.commit()

        # Adds the album to the database
        new_album = Albums(name=album_name, year=year,
                           fk_product_id=id, fk_artist_id=artist.artist_id)

        # Updates the AlbumGenre table with genres that are associated with the album
        for genre in request.form.getlist('genres'):
            album_genre = AlbumGenre(fk_album_id=id, fk_genre_id=genre)
            db.session.add(album_genre)
            db.session.commit()

        db.session.add(new_album)
        db.session.commit()

        return redirect(url_for('admin.admin_products'))

    return render_template('adminProductDetailsSet.html', details_form=details_form)


# Route for deleting songs from albums

@admin_bp.route('products/details/delete/<int:product_id>/<int:song_id>', methods=['GET', 'POST'])
@role_required('Admin')
def delete_song(product_id, song_id):
    """Function for deleting songs from the database"""

    # Queries the database for song with correct id
    song = db.session.query(Songs).get(song_id)
    # If the song is in the database
    if song:
        # Deletes the song
        db.session.delete(song)
        db.session.commit()
        flash('Song Deleted Successfully', 'success')
    else:
        flash('Song Not Found', 'Error')

    return redirect(url_for('admin.admin_product_details', id=product_id))


# Route for managing users

@admin_bp.route('/users', methods=['GET', 'POST'])
@role_required('Admin')
def admin_users():
    """Function for loading the admin user management page"""

    # Initialises the user edit form class
    user_form = UserEditForm()
    # Queries the database for all user data
    users = db.session.query(Users).all()

    # If user edit form is submitted
    if user_form.validate_on_submit():
        # Queries the database for the user being edited
        user = db.session.query(Users).filter_by(
            username=user_form.username.data).first()
        # Updates the fields with data from the user_form
        user_form.populate_obj(user)
        db.session.commit()
        flash('User Edited Successfully', 'success')

    return render_template('adminUsers.html', user_form=user_form, users=users)


# Route for deleting users

@admin_bp.route('users/delete/<id>', methods=['GET', 'POST'])
@role_required('Admin')
def delete_user(id):
    # Queries the database for the user being deleted
    user = db.session.query(Users).get(id)
    db.session.delete(user)
    db.session.commit()
    flash('Product Deleted Successfully', 'success')

    return redirect(url_for('admin.admin_users'))


# Route for website analysis

@admin_bp.route('/analysis')
@role_required('Admin')
def admin_analysis():
    """Function for querying and displaying website data for analysis"""

    # Queries and aligns orderitem data based on quantity and returns the top 5 most popular
    most_popular_products = db.session.query(Products.name, func.sum(OrderItems.quantity).label('total_quantity')) \
        .join(OrderItems) \
        .group_by(Products.name) \
        .order_by(func.sum(OrderItems.quantity).desc()) \
        .limit(5) \
        .all()

    # Queries and aligns order data based on money made at a given time
    revenue_over_time = db.session.query(func.datetime(Orders.date_added).label('datetime'), func.sum(OrderItems.quantity * Products.price).label('revenue')).join(OrderItems, Orders.order_id == OrderItems.fk_order_id)\
        .join(Products, OrderItems.fk_product_id == Products.product_id)\
        .group_by(func.extract('hour', Orders.date_added))\
        .order_by(func.extract('hour', Orders.date_added)).all()

    print(revenue_over_time)
    # Saves the labels and values for the top 5 most popular products in a tuple
    most_popular = ([label[0] for label in most_popular_products], [
                    value[1] for value in most_popular_products])
    # Saves the labels and values for the revenue earnt over time
    revenue_time = ([label[0] for label in revenue_over_time],
                    [value[1] for value in revenue_over_time])

    return render_template('adminAnalysis.html', most_popular=most_popular, revenue_time=revenue_time)

app/admin/templates/admin.html
{% extends 'base.html' %}
{% include 'headers/adminHeader.html' %}

{% block title %} Home {% endblock %}


{% block body %}
<div class="text-white d-flex justify-content-center">
  <h1>Welcome Admin {{ current_user.username }}</h1>
</div>
{% endblock %}

app/admin/templates/adminAnalysis.html
{% extends 'base.html' %}
{% include 'headers/adminHeader.html' %}

{% block body %}
<style>
  .chart-container {
    width: 50%;
    height: 50%;
    margin: auto;
  }
</style>

<div class="jumbotron p-3">
  <h3 class="text-white d-flex justify-content-center">Website Analysis</h3>
</div>
<div class="card chart-container text-white" style="background-color: rgb(41, 41, 41); margin-bottom: 30px;">
  <h5 class="d-flex justify-content-center">Top 5 Products</h5>
  <canvas id="mostPopularChart"></canvas>
</div>
<div class="card chart-container text-white" style="background-color: rgb(41, 41, 41);">
  <h5 class="d-flex justify-content-center">Revenue Over Time</h5>
  <canvas id="revenueByHourChart"></canvas>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js">
</script>
<script>
  function createChart(title, labels, values, context, type) {
    const myChart = new Chart(context, {
      type: type,
      data: {
        labels: labels,
        datasets: [{
          label: title,
          backgroundColor: '#FF9900',
          borderColor: 'black',
          data: values,
        }]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true,
            }
          }]
        }
      },
    });
  }

  const most_popular_context = document.getElementById("mostPopularChart").getContext('2d');
  const most_popular_labels = {{ most_popular[0] | tojson }};
  const most_popular_values = {{ most_popular[1] | tojson }};
  createChart('Products Sold', most_popular_labels, most_popular_values, most_popular_context, 'bar')

  const revenue_time_context = document.getElementById("revenueByHourChart").getContext('2d')
  const revenue_time_labels = {{ revenue_time[0] | tojson }};
  const revenue_time_values = {{ revenue_time[1] | tojson }};
  createChart('Revenue by Hour', revenue_time_labels, revenue_time_values, revenue_time_context, 'line')
</script>

</html>
{% endblock %}

app/admin/templates/adminProductDetails.html
{% extends 'base.html' %}
{% include 'headers/adminHeader.html' %}

{% block title %} Home {% endblock %}


{% block body %}

<div class="container text-white">
  <h1><i>{{ product.name }}</i> Product Details</h1>
  <h3>Album Name</h3>
  {{product.music_info.name}}
  <h3>Release Year</h3>
  {{product.music_info.year}}
  <h3>Genres</h3>
  <ul class="list-inline">
    {% for genre in genres %}
    <li class="list-inline-item">{{ genre.name }}</li>
    {% endfor %}
  </ul>

  <h3>Artist Name</h3>
  {{ product.music_info.artists.name }}
  <h3>Artist Bio</h3>
  {{ product.music_info.artists.bio }}
</div>

<div class="container text-white">
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron p-3">
        <h2>Manage Songs
          <button type="button" class="btn btn-success float-end" data-bs-toggle="modal"
            data-bs-target="#addsongmodal">Add New Song</button>
        </h2>

        {% with messages = get_flashed_messages() %}

        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-success alert-dismissable" role="alert">
          {{ message }}
          <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {% endfor %}
        {% endif %}
        {% endwith%}
        <table class="table table-hover table-dark">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Length</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          {% for song in product.music_info.songs: %}
          <tr>
            <td>{{ song.song_id }}</td>
            <td>{{ song.name }}</td>
            <td>{{ song.length }} seconds</td>
            <td><a class="btn btn-warning btn-xs" data-bs-toggle="modal" data-bs-target="#editsongmodal">Edit</a></td>
            <td><a href="{{url_for('admin.delete_song', product_id=product.product_id, song_id=song.song_id)}}"
                type="button" class="btn btn-danger btn-xs"
                onclick="return confirm('Confirm Product {{song.song_id}} Deletion')">Delete</button></td>
          </tr>
          <!-- Edit Song Modal -->
          <div class="modal fade" id="editsongmodal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dark">
              <div class="modal-content bg-dark">
                <div class="modal-header">
                  <h5 class="modal-title text-black" id="staticBackdropLabel">Edit Song</h5>
                </div>
                <form action="" method="POST">
                  {{ song_form.csrf_token }}
                  {{ song_form.hidden_tag() }}
                  <div class="modal-body">
                    <div class="form-group">
                      {{ song_form.song_id.label }}
                      {{ song_form.song_id(value=song.song_id, class="form-control", type="number",
                      readonly="true") }}
                    </div>
                    <div class="form-group">
                      <label>{{ song_form.name.label }}</label>
                      {{ song_form.name(value=song.name, class="form-control bg-secondary text-white") }}
                    </div>
                    <div class="form-group">
                      <label>{{ song_form.length.label }}</label>
                      {{ song_form.length( value=song.length, class="form-control bg-secondary text-white") }}
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    {{ song_form.submit(class="btn btn-warning") }}
                  </div>
                </form>
              </div>
            </div>
          </div>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</div>


<!-- Add Song Modal -->
<div class="modal fade" id="addsongmodal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dark">
    <div class="modal-content bg-dark">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Add Song</h5>
      </div>
      <form action="" method="POST">
        {{ song_form.csrf_token }}
        {{ song_form.hidden_tag() }}
        <div class="modal-body">
          <div class="form-group">
            <label>{{ song_form.name.label }}</label>
            {{ song_form.name(class="form-control bg-secondary text-white") }}
          </div>
          <div class="form-group">
            <label>{{ song_form.length.label }}</label>
            {{ song_form.length(class="form-control bg-secondary text-white") }}
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          {{ song_form.submit(class="btn btn-primary") }}
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

app/admin/templates/adminProductDetailsSet.html
{% extends 'base.html' %}
{% include 'headers/adminHeader.html' %}

{% block title %} Home {% endblock %}


{% block body %}
<div class="container text-white">
  <h3>Add Product Details</h3>
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron p-3">
        <form action="" method="POST">
          {{ details_form.csrf_token }}
          {{ details_form.hidden_tag() }}
          <div class="modal-body">
            <div class="form-group">
              <label>{{ details_form.album_name.label }}</label>
              {{ details_form.album_name(class="form-control bg-secondary text-white") }}
            </div>
            <div class="form-group">
              <label>{{ details_form.year.label }}</label>
              {{ details_form.year(class="form-control bg-secondary text-white") }}
            </div>
            <div class="form-group">
              <label>{{ details_form.artist_name.label }}</label>
              {{ details_form.artist_name(class="form-control bg-secondary text-white") }}
            </div>
            <div class="form-group">
              <label>{{ details_form.artist_bio.label }}</label>
              {{ details_form.artist_bio(class="form-control bg-secondary text-white") }}
            </div>
            <div class="form-group">
              <label>{{ details_form.genres.label }}</label>
              {{ details_form.genres(class="form-control list-unstyled bg-secondary text-white") }}
            </div>
          </div>
          <div class="modal-footer">
            <a href="{{ url_for('admin.admin_products')}}"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button></a>
            {{ details_form.submit(class="btn btn-primary") }}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/admin/templates/adminProducts.html
{% extends 'base.html' %}
{% include 'headers/adminHeader.html' %}

{% block title %} Home {% endblock %}


{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron p-3">
        <h2>Manage Products <button type="button" class="btn btn-success float-end" data-bs-toggle="modal"
            data-bs-target="#addproductmodal">Add New Product</button></h2>

        {% with messages = get_flashed_messages() %}

        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-success alert-dismissable" role="alert">
          {{ message }}
          <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {% endfor %}
        {% endif %}
        {% endwith%}

        <table class="table table-hover table-dark">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Image</th>
            <th>Price</th>
            <th>Type</th>
            <th>Stock Count</th>
            <th>Product Details</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          {% for product in products: %}
          <tr>
            <td>{{ product.product_id }}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.image }}</td>
            <td>£{{ product.price }}</td>
            <td>{{ product.type }}</td>
            <td>{{ product.stock }}</td>
            <td>
              {% if product.music_info %}
              <a href="{{ url_for('admin.admin_product_details', id=product.product_id) }}"
                class="btn btn-success btn-xs">View Details/Song Management</a>
              {% else %}
              <a href="{{ url_for('admin.set_product_details', id=product.product_id) }}"
                class="btn btn-success btn-xs">Set Details</a>
              {% endif %}
            </td>
            <td><a class="btn btn-warning btn-xs" data-bs-toggle="modal"
                data-bs-target="#editproductmodal{{product.product_id}}">Edit</a></td>
            <td><a href="{{ url_for('admin.delete_product', id=product.product_id)}}" type="button"
                class="btn btn-danger btn-xs"
                onclick="return confirm('Confirm Product {{product.product_id}} Deletion')">Delete</button></td>
          </tr>


          <!-- Edit Product Modal -->
          <div class="modal fade" id="editproductmodal{{ product.product_id }}" data-bs-backdrop="static"
            data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dark">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">Edit Product</h5>
                </div>
                <form action="" method="POST">
                  {{ product_form.csrf_token }}
                  {{ product_form.hidden_tag() }}
                  <div class="modal-body">
                    <div class="form-group">
                      {{ product_form.product_id.label }}
                      {{ product_form.product_id(value=product.product_id, class="form-control", type="number",
                      readonly="true") }}
                    </div>
                    <div class="form-group">
                      {{ product_form.name.label }}
                      {{ product_form.name(class="form-control", value=product.name) }}
                    </div>
                    <div class="form-group">
                      {{ product_form.image.label }}
                      {{ product_form.image(class="form-control", value=product.image) }}
                    </div>
                    <div class="form-group">
                      {{ product_form.price.label }}
                      {{ product_form.price(class="form-control", type="number", value=product.price) }}
                    </div>
                    <div class="form-group">
                      {{ product_form.type.label }}
                      {{ product_form.type(class="form-control", value=product.type) }}
                    </div>
                    <div class="form-group">
                      {{ product_form.stock.label }}
                      {{ product_form.stock(class="form-control", value=product.stock) }}
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    {{ product_form.submit(class="btn btn-primary") }}
                  </div>
                </form>
              </div>
            </div>
          </div>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</div>

<!-- Add Product Modal -->
<div class="modal fade" id="addproductmodal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dark">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Add Product</h5>
      </div>
      <form action="" method="POST">
        {{ product_form.csrf_token }}
        {{ product_form.hidden_tag() }}
        <div class="modal-body">
          <div class="form-group">
            <label>{{ product_form.name.label }}</label>
            {{ product_form.name(class="form-control") }}
          </div>
          <div class="form-group">
            <label>{{ product_form.image.label }}</label>
            {{ product_form.image(class="form-control") }}
          </div>
          <div class="form-group">
            <label>{{ product_form.price.label }}</label>
            {{ product_form.price(class="form-control", type="number") }}
          </div>
          <div class="form-group">
            <label>{{ product_form.type.label }}</label>
            {{ product_form.type(class="form-control") }}
          </div>
          <div class="form-group">
            <label>{{ product_form.stock.label }}</label>
            {{ product_form.stock(class="form-control") }}
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          {{ product_form.submit(class="btn btn-primary") }}
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  function makePutRequest(endpoint, id, data) {
    var url = `${endpoint}/${id}`;
    var formData = new FormData(document.getElementById('editproductmodal'));
    var data = {};
    formData.forEach(function(value, key){
        data[key] = value;
    });
    fetch(url, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    })
      .then(response => {
        if (!response.ok) {
          throw new Error('Network response was not ok');
        }
        return response.json();
      })
      .then(data => {
        console.log(data);
        alert('PUT request successful');
      })
      .catch(error => {
        console.error('There was a problem with the request:', error);
        alert('Failed to make PUT request');
      });
  }
</script>

{% endblock %}

app/admin/templates/adminUsers.html
{% extends 'base.html' %}
{% include 'headers/adminHeader.html' %}

{% block title %} Home {% endblock %}


{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron p-3">
        <h2>Manage Users</h2>

        {% with messages = get_flashed_messages() %}

        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-success alert-dismissable" role="alert">
          {{ message }}
          <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {% endfor %}
        {% endif %}
        {% endwith%}

        <table class="table table-hover table-dark">
          <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Email</th>
            <th>Role</th>
            <th>Date Created</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          {% for user in users: %}
          <tr>
            <td>{{ user.user_id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.type }}</td>
            <td>{{ user.date_added }}</td>
            <td><a class="btn btn-warning btn-xs" data-bs-toggle="modal"
                data-bs-target="#editusermodal{{user.user_id}}">Edit</a></td>
            <td><a href="{{ url_for('admin.delete_user', id=user.user_id)}}" type="button" class="btn btn-danger btn-xs"
                onclick="return confirm('Confirm User {{user.user_id}} Deletion')">Delete</button></td>
          </tr>

          <!-- Edit User Modal -->
          <div class="modal fade" id="editusermodal{{ user.user_id }}" data-bs-backdrop="static"
            data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">Edit User</h5>
                </div>
                <form action="" method="POST">
                  {{ user_form.csrf_token }}
                  {{ user_form.hidden_tag() }}
                  <div class="modal-body">
                    <div class="form-group">
                      {{ user_form.username.label }}
                      {{ user_form.username(class="form-control", value=user.username) }}
                    </div>
                    <div class="form-group">
                      {{ user_form.email.label }}
                      {{ user_form.email(class="form-control", value=user.email) }}
                    </div>
                    <div class="form-group">
                      {{ user_form.type.label }}
                      {{ user_form.type(class="form-control", type="number", value=user.type) }}
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    {{ user_form.submit(class="btn btn-primary") }}
                  </div>
                </form>
              </div>
            </div>
          </div>

          {% endfor %}

        </table>

      </div>
    </div>
  </div>
</div>

{% endblock %}