app/categories/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
from sqlalchemy import func

from app.forms import FilterForm
from app.models import AlbumGenre, Albums, Artists, Genres, OrderItems, Products
from app.extensions import db

# Initialisation of the category blueprint
category_bp = Blueprint('categories', __name__, template_folder='templates')


# Route for music category

@category_bp.route('/music', methods=['GET', 'POST'])
def music():
    """Function for rendering the music category page"""

    # Initialises the filter form class
    filter_form = FilterForm()

    # Sets the options for the artists filter
    filter_form.artist.choices = [(str(artist.artist_id), artist.name)
                                  for artist in db.session.query(Artists.artist_id, Artists.name).all()]
    # Adds a no filter option for the artist filter
    filter_form.artist.choices.insert(0, ('no_filter', 'No Filter'))

    # Sets the options for the genre filter
    filter_form.genre.choices = [(str(genre.genre_id), genre.name)
                                 for genre in db.session.query(Genres.genre_id, Genres.name).all()]
    # Adds a no filter option for the genre filter
    filter_form.genre.choices.insert(0, ('no_filter', 'No Filter'))

    if filter_form.validate_on_submit():
        return redirect(url_for('categories.music_filters', artist=filter_form.artist.data, genre=filter_form.genre.data))

    # Queries database for the top 10 most popular products determined by quantity sold
    popular_products = Products.query.join(OrderItems, Products.product_id == OrderItems.fk_product_id) \
        .group_by(Products.product_id)\
        .order_by(func.sum(OrderItems.quantity).desc()) \
        .limit(10).all()

    # Sets query for collating the music products and their related data
    products = db.session.query(Products).join(Albums).join(Artists).join(
        AlbumGenre).join(Genres).filter(Products.type == 'music')

    # Queries the database
    products = products.all()

    return render_template('categoryPage.html', page_name="music", products=products, popular_products=popular_products, filter_form=filter_form)


# Route for the filtered products page

@category_bp.route('/filters')
def music_filters():
    """Function for rendering the filter page for music products"""

    # Queries database for music products and their relevant data
    products = Products.query.filter_by(type='music').join(Albums).join(Artists).join(
        AlbumGenre).join(Genres)
    # Retrieves the chosen genre for filtering
    genre = request.args.get('genre')
    # Retireves the chosen artist for filtering
    artist = request.args.get('artist')

    if artist != 'no_filter':
        # Do artist filtering
        products = products.filter(
            Artists.artist_id == artist)
    if genre != 'no_filter':
        # Do genre filtering
        print(request.args.get('genre'))
        products = products.filter(
            Genres.genre_id == genre)
    products = products.all()

    return render_template('musicFilters.html', products=products, genre=genre, artist=artist)


# Route for individual product page

@category_bp.route('/<int:product_id>')
def get_product_page(product_id: int):
    """Function for rendering individual product page"""

    # Queries database for product based on id
    product = db.session.query(Products).filter(
        Products.product_id == product_id).first()
    # Queries database for album based on id
    album = db.session.query(Albums).filter(
        Albums.fk_product_id == product.product_id).first()
    # If product exists
    if product:
        return render_template('productPage.html', product=product, album=album)
    else:
        return 'Product not found', 404


# Route for animals category

@category_bp.route('/animals')
def animals():
    """Function for rendering the animals category page"""
    return render_template('categoryPage.html', page_name="Animals")


# Route for books category

@category_bp.route('/books')
def books():
    """Function for rendering the books category page"""
    return render_template('categoryPage.html', page_name="Books")


# Route for car parts category

@category_bp.route('/carparts')
def car_parts():
    """Function for rendering the carparts category page"""
    return render_template('categoryPage.html', page_name="Car Parts")


# Route for phones category

@category_bp.route('/phones')
def phones():
    """Function for rendering the phones category page"""
    return render_template('categoryPage.html', page_name="Phones")

# Route for sports category


@category_bp.route('/sports')
def sports():
    """Function for rendering the sports category page"""
    return render_template('categoryPage.html', page_name="Sports")

app/categories/templates/categoryPage.html
{% extends 'base.html' %}
{% include 'headers/productHeader.html' %}
{% block body %}
<script>categoryIdentifier()</script>
<h1 class="text-white d-flex justify-content-center" style="text-transform: capitalize">{{page_name}} Page</h1>
{% if products %}
<div class="trendingProducts" id="productBar"
    style="background-color: orange; border-radius: 25px; margin: 10px; padding: 15px;">
    <h3 style="padding-left:25px; margin-top: 5px;">Trending Right Now</h3>
    <div class="productBar">
        <div class="card-group">
            {% for product in popular_products: %}
            <div class="col-sm-6 col-md-2 col-lg-1" style="margin:10px;">
                <a href="{{ url_for('categories.get_product_page', product_id=product.product_id) }}">
                    <div class="card h-100" style="border-radius: 25px;">
                        <img src="..\static\products_artwork\{{ product.image }}"
                            style="border-top-left-radius: 25px; border-top-right-radius: 25px;"
                            alt="{{ product.name }} album art">
                        <div class="card-body justify-content-center">
                            <p class="card-text">{{ loop.index }}. {{ product.name }}</p>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="productSection" style="background-color: lightgrey; border-radius: 25px; margin: 10px; padding: 15px;">
    {% if page_name == "music" %}
    <div id="productHeader"
        class="container-fluid d-flex flex-column flex-md-row align-items-center justify-content-between"
        style="background-color: grey; border-radius: 50px; height: 105%; padding: 15px;">
        <div class="d-flex flex-column flex-md-row align-items-md-center">
            <div class="d-flex justify-content-center">
                <button type="button" class="btn btn-primary btn-sm mb-2 mb-md-0" data-bs-toggle="modal"
                    data-bs-target="#filterModal">
                    <h4>Filter</h4>
                </button>
            </div>
            <form id="productSortForm" class="row mx-2" action="/{{ page_name }}" method="POST">
                <input type="hidden" name="sortFormId" value="sortForm">
                <div class="col-auto d-flex align-items-center">
                    <label for="sortOptions" class="form-label mb-0">
                        <h4>Sort:</h4>
                    </label>
                </div>
                <div class="col-auto">
                    <select name="sort" id="sortOptions" class="form-select w-auto">
                        <option value="descend">Release Year: Newest to Oldest</option>
                        <option value="ascend">Release Year: Oldest to Newest</option>
                    </select>
                </div>
            </form>
        </div>
        <div>
            <h4>{{ products | length }} Result{% if products | length > 1 %}s{% endif %}</h4>
        </div>
    </div>
    {% endif %}
    <div class="card-group" id="products">
        {% for product in products: %}
        <div class="col-sm-6 col-md-4 col-lg-2 product" data-year="{{ product.music_info.year }}"
            style="margin-bottom: 20px;">
            <a id="product {{ product.product_id }}"
                href="{{ url_for('categories.get_product_page', product_id=product.product_id) }}">
                <div class="card h-100" style="border-radius: 25px; margin: 10px;">
                    <img src="..\static\products_artwork\{{ product.image }}"
                        style="border-top-left-radius: 25px; border-top-right-radius: 25px;"
                        alt="{{ product.name }} album art">
                    <div class="card-body justify-content-center">
                        <h3 class="card-text">{{ product.name }}</h3>
                        <h5 class="card-text prices">{{ product.price }}</h5>
                        <script>priceConversion('h5', 'prices')</script>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<script>
    document.getElementById('sortOptions').addEventListener('change', sortProductYear);
    sortProductYear();
</script>

</div>
<div class="modal fade" id="filterModal" tabindex="-1" aria-labelledby="filterModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="filterModalLabel">Filters</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post">
                    {{ filter_form.csrf_token }}
                    {{ filter_form.hidden_tag() }}
                    {{ filter_form.artist.label }}
                    {{ filter_form.artist(class="form-control") }}
                    {{filter_form.genre.label }}
                    {{filter_form.genre(class="form-control") }}
            </div>
            <div class="modal-footer">
                {{ filter_form.submit(class="btn btn-primary") }}
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}
<h1>{{ page_name }} Page Coming Soon</h1>
{% endif %}
{% endblock %}

app/categories/templates/musicFilters.html
{% extends 'base.html' %}
{% include 'headers/productHeader.html' %}
{% block body %}
<h3 class="text-white" style="margin: 20px;">{{ products | length }} Result{% if products | length > 1 %}s{% endif %}</h3>
<div class="card-group">
    {% for product in products: %}
    <div class="col-md-2" style="margin: 10px;">
        <a href="{{ url_for('categories.get_product_page', product_id=product.product_id) }}">
            <div class="card" style="margin: 20px;  border-radius: 25px;">
                <img src="..\static\products_artwork\{{ product.image }}" alt="{{ product.name }} album art" style="border-top-left-radius: 25px; border-top-right-radius: 25px;">
                <div class="card-body">
                    <p class="card-text">{{ product.name }}</p>
                    <p class="card-text prices">{{ product.price }}</p>
                    <script>priceConversion('p', 'prices')</script>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/categories/templates/productPage.html
{% extends 'base.html' %}
{% include 'headers/productHeader.html' %}
{% block body %}
<div style="margin-left: 50px; margin-right: 50px;">
    <div class="row" style="padding: 10px; border-radius: 25px;">
        <div class="box col-lg-3 d-flex justify-content-center">
            <div class="d-flex justify-content-center">
                <img src="../static/products_artwork/{{ product.image }}" alt="artwork"
                    style="border-radius: 25px; max-width: 100%; margin: auto;">
            </div>
        </div>
        <div class="box col-lg-6 text-white"">
            <h2 style=" display: inline; margin-right: 10px;">{{ product.name }}</h2>
            {% if product.music_info %}
            <h6 style="display: inline;"><i>{{ product.music_info.artists.name }}</i></h6>
            {% else %}
            <h6 style="display: inline;"><i>Unknown Artist</i></h6>
            {% endif %}
            <div class="table-container" style="overflow-y: scroll; max-height: 300px; margin: 10px;">
                <table class="table table-hover table-dark">
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Length</th>
                    </tr>
                    {% for song in album.songs: %}
                    <tr>
                        <td>{{ song.song_id }}</td>
                        <td>{{ song.name }}</td>
                        <td>{{ song.length }} Seconds</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="box col-lg-3 d-flex align-items-center">
            <div class="container text-white">
                <div class="row">
                    <div class="col-md-12 d-flex justify-content-center">
                        <h2><i>Format</i></h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 d-flex justify-content-center">
                        <form action="{{url_for('basket.add_to_basket')}}" method="POST">
                            <input type="hidden" name="product_id" value="{{ product.product_id }}">
                            <div class="list-group">
                                <label class="btn btn-primary list-group-item">
                                    <input class="form-check-input" type="radio" name="options" value="Vinyl" checked> Vinyl
                                </label>
                                <label class="btn btn-primary list-group-item">
                                    <input class="form-check-input" type="radio" name="options" value="CD"> CD
                                </label>
                                <label class="btn btn-primary list-group-item">
                                    <input class="form-check-input" type="radio" name="options" value="Cassette"> Cassette
                                </label>
                                <label class="btn btn-primary list-group-item">
                                    <input class="form-check-input" type="radio" name="options" value="Digital"> Digital
                                </label>
                            </div>
                            <div class="row" style="margin: auto;">
                                <label for="quantityField">Quantity:</label>
                                <select id="quantityField" name="quantity">
                                    {% for quantity in range(1, 6) %}
                                    <option value="{{ quantity }}">{{ quantity }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div style="margin-top: 10px">
                                <h5 class="prices" style="display: inline;">{{ product.price }}</h5>
                                <script>priceConversion('h5', 'prices')</script>
                                <button class="btn btn-primary" type="submit">Add to Basket</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">

            </div>
        </div>
    </div>
    <div class="row">
        <div class="box col-lg-9 text-white;">
            {% if product.music_info %}
            <h3 class="text-white"><i>{{ album.artists.name }} Bio</i></h3>
            <p class="text-white">{{ album.artists.bio }}</p>
            {% else %}
            <h3 class="text-white"><i>Unknown Artist</i></h3>
            ...
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}